# Generated by Django 5.0.1 on 2024-02-05 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_remove_comment_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="publish",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="active",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="email",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="level",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="lft",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="name",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="rght",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="tree_id",
        ),
        migrations.AddField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
