name: Blog APP CI

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11 # Change this to your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Adjust the path to your requirements file

      - name: Run tests
        run: pytest

  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout master
        uses: actions/checkout@v1
      - name: Add environment variables to .env
        run: |
          echo DEBUG=${{ secrets.DEBUG }} >> .env
          echo ADMIN_INTERNAL_URL=${{ secrets.ADMIN_INTERNAL_URL }} >> .env
          echo DATABASE_ENGINE=django.db.backends.postgresql >> .env
          echo DATABASE=postgres >> .env
          echo DJANGO_SECRET_KEY="${{ secrets.SECRET_KEY }}" >> .env
          echo DJANGO_ALLOWED_HOSTS=${{ secrets.DJANGO_ALLOWED_HOSTS }} >> .env
          echo DATABASE_NAME=${{ secrets.DATABASE_NAME }} >> .env
          echo DATABASE_USER=${{ secrets.DATABASE_USER }} >> .env
          echo DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} >> .env
          echo DATABASE_HOST=${{ secrets.DATABASE_HOST }} >> .env
          echo DATABASE_PORT=${{ secrets.DATABASE_PORT }} >> .env
          echo POSTGRES_DB=${{ secrets.DATABASE_NAME }} >> .env
          echo POSTGRES_USER=${{ secrets.DATABASE_USER }} >> .env
          echo POSTGRES_PASSWORD=${{ secrets.DATABASE_PASSWORD }} >> .env
      - name: ssh-agent
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-copy-id ${{ secrets.SSH_KEY }} zayyadev@zayadev.xyz
          echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_rsa

      - name: Build and Deploy
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          scp  -o StrictHostKeyChecking=no -r ./.env zayyadev@zayadev.xyz:/opt/usr/devs/
          ssh -o StrictHostKeyChecking=no zayyadev@zayadev.xyz << 'ENDSSH'
            cd /opt/usr/devs/
            git pull origin master --force
            cd dj_user
            python3.11 -m pip install virtualenv
            python3.11 -m virtualenv venv
            source ./venv/bin/activate
            pip install --upgrade pip
            pip install wheel
            pip install -r requirements.txt
            bash ./build/migrations.sh
            chmod +x ./deploy/start_gunicorn
            chmod u+x ./terminate.sh
            sudo service supervisor restart
            sudo nginx -t && sudo service nginx reload
          ENDSSH
